name: bilbomaxrm
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  pdf: ^3.10.7
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

# Configuración de Icono de la App
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "assets/logo.png"

# Configuración de Pantalla de Bienvenida
flutter_native_splash:
  color: "#1A1A1A"
  image: assets/logo.png
  android: true
  ios: true
  fullscreen: true